# Visualise output tabular table generated by https://github.com/sanger-pathogens/assembly-stats
# Using radar plots to compare assemblies
# cmdoret, 20190607

library(tidyverse)
library(ggiraphExtra)
library(scales)
library(tools)


args <- commandArgs(trailingOnly=T)

minscale <- function(x){s = scale(x); return(s + abs(min(s)))}
assemblies <- read_tsv(args[1]) %>%
  rename(n_contigs=number, assembly=filename) %>%
  mutate(assembly=file_path_sans_ext(basename(assembly))) %>%
  mutate_at(vars(-assembly), minscale ) %>%
  select(assembly, total_length, n_contigs, N50, N70, N90, N70n, N90n)

svg(args[2])
ggRadar(assemblies, aes(group = assembly), 
             rescale=F, legend.position = "none", scales="fixed",
             size = 1, interactive = FALSE, use.label = TRUE, ylim=c(-1., 1.)) +
  facet_wrap(~assembly) + 
  ggtitle("Acanthamoeba castellanii Neff: Genome assemblies stats") + 
  theme_bw()
dev.off()